
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Label label1;

	private global::Gtk.Entry entrySub;

	private global::Gtk.Button buttonSubscribe;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Where");
		this.fixed1.Add(this.label1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
		w1.X = 37;
		w1.Y = 52;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entrySub = new global::Gtk.Entry();
		this.entrySub.CanFocus = true;
		this.entrySub.Name = "entrySub";
		this.entrySub.IsEditable = true;
		this.entrySub.InvisibleChar = '●';
		this.fixed1.Add(this.entrySub);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entrySub]));
		w2.X = 161;
		w2.Y = 46;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.buttonSubscribe = new global::Gtk.Button();
		this.buttonSubscribe.CanFocus = true;
		this.buttonSubscribe.Name = "buttonSubscribe";
		this.buttonSubscribe.UseUnderline = true;
		this.buttonSubscribe.Label = global::Mono.Unix.Catalog.GetString("Subscribe");
		this.fixed1.Add(this.buttonSubscribe);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.buttonSubscribe]));
		w3.X = 156;
		w3.Y = 172;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.buttonSubscribe.Clicked += new global::System.EventHandler(this.OnButtonSubscribeClicked);
	}
}
